/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import dao.DPersona;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.sexo;

/**
 *
 * @author labc205
 */
public class FrmPersona extends javax.swing.JFrame {
    DPersona dp = new DPersona();

    /**
     * Creates new form FrmPersona
     */
    public FrmPersona() {
        initComponents();
        jBtnLIM.setToolTipText("Limpiar");
        jBtnAGR.setToolTipText("Agregar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLblID = new javax.swing.JLabel();
        jLblNOM = new javax.swing.JLabel();
        jLblAPE = new javax.swing.JLabel();
        jLblEMA = new javax.swing.JLabel();
        jLblSEX = new javax.swing.JLabel();
        jTfID = new javax.swing.JTextField();
        jTfNOM = new javax.swing.JTextField();
        jTfAPE = new javax.swing.JTextField();
        jTfEMA = new javax.swing.JTextField();
        jCbSEX = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        jBtnLIM = new javax.swing.JButton();
        jBtnAGR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblREG = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listado de Personas");

        jLblID.setText("ID:");

        jLblNOM.setText("Nombres:");

        jLblAPE.setText("Apellidos:");

        jLblEMA.setText("Email:");

        jLblSEX.setText("Sexo:");

        jCbSEX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Hombre", "Mujer" }));
        jCbSEX.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jCbSEXAncestorRemoved(evt);
            }
        });
        jCbSEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbSEXActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        jBtnLIM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complementos/img/nuevo.png"))); // NOI18N
        jBtnLIM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnLIM.setFocusable(false);
        jBtnLIM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnLIM.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnLIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLIMActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnLIM);

        jBtnAGR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complementos/img/guardar.png"))); // NOI18N
        jBtnAGR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnAGR.setFocusable(false);
        jBtnAGR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAGR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnAGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAGRActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnAGR);

        jTblREG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTblREG);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblNOM)
                            .addComponent(jLblAPE)
                            .addComponent(jLblID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblEMA, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblSEX, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTfAPE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jTfID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbSEX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfNOM, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTfEMA)))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblID)
                    .addComponent(jTfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNOM)
                    .addComponent(jTfNOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblAPE)
                    .addComponent(jTfAPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEMA)
                    .addComponent(jTfEMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblSEX)
                    .addComponent(jCbSEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLIMActionPerformed
        // TODO add your handling code here:
        llenarTabla();
        Limpiar();
    }//GEN-LAST:event_jBtnLIMActionPerformed

    private void jCbSEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbSEXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbSEXActionPerformed

    private void jCbSEXAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jCbSEXAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbSEXAncestorRemoved

    private void jBtnAGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAGRActionPerformed
        // TODO add your handling code here:
        if(jTfID.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Necesita agregar el ID",
                    "Guardar",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
         if(jTfNOM.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Necesita agregar el NOMBRE",
                    "Guardar",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int id = Integer.parseInt(jTfID.getText());
        String nom = jTfNOM.getText();
        String ape = jTfAPE.getText();
        String ema = jTfEMA.getText();
        sexo s ;
        if (jCbSEX.getSelectedIndex()== 1) s = sexo.HOMBRE;
        else s = sexo.MUJER;
        
        int b = dp.agregarPersona(id, nom, ape, ema, s);
        if (b == 1){
            JOptionPane.showMessageDialog(this, "Resgistro Agregado...", 
                    "Guardar", JOptionPane.INFORMATION_MESSAGE);
            Limpiar();
        }else {
            JOptionPane.showMessageDialog(this, "Error al guardar...", "Guardar", JOptionPane.ERROR_MESSAGE);
        }
        
        llenarTabla();
        
    }//GEN-LAST:event_jBtnAGRActionPerformed

    private void llenarTabla(){
     DefaultTableModel tbl = new DefaultTableModel();
     tbl = dp.getListPers();
     jTblREG.setModel(tbl);
    }
    
    private void Limpiar(){
        jTfID.setText("");
        jTfNOM.setText("");
        jTfAPE.setText("");
        jTfEMA.setText("");
        jCbSEX.setSelectedIndex(0);
        jTfID.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAGR;
    private javax.swing.JButton jBtnLIM;
    private javax.swing.JComboBox<String> jCbSEX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblAPE;
    private javax.swing.JLabel jLblEMA;
    private javax.swing.JLabel jLblID;
    private javax.swing.JLabel jLblNOM;
    private javax.swing.JLabel jLblSEX;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblREG;
    private javax.swing.JTextField jTfAPE;
    private javax.swing.JTextField jTfEMA;
    private javax.swing.JTextField jTfID;
    private javax.swing.JTextField jTfNOM;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
